name: 🐞 Correção de Bug
description: Relate um problema ou comportamento inesperado no sistema
labels: ["bug"]
title: "[FIX]: "
assignees: ["guiigos"]

body:
  - type: markdown
    attributes:
      value: |
        **Antes de criar a issue**, verifique se o problema já foi relatado.
        Consulte as *issues* abertas/fechadas para evitar duplicidade.

  - type: textarea
    id: descricao
    attributes:
      label: Descrição do Problema
      description: Explique resumidamente o bug encontrado.
      placeholder: "Informe o que está acontecendo de forma clara."
    validations:
      required: true

  - type: textarea
    id: comportamento-atual
    attributes:
      label: Comportamento Atual
      description: Descreva exatamente o que está acontecendo no sistema.
      placeholder: "Explique o comportamento observado."
    validations:
      required: true

  - type: textarea
    id: comportamento-esperado
    attributes:
      label: Comportamento Esperado
      description: Informe qual deveria ser o comportamento correto.
      placeholder: "Descreva o funcionamento esperado."
    validations:
      required: true

  - type: textarea
    id: passos-reproducao
    attributes:
      label: Passos para Reproduzir
      description: Explique como reproduzir o problema.
      placeholder: "Liste os passos para reproduzir o bug."
    validations:
      required: false

  - type: textarea
    id: ambiente
    attributes:
      label: Ambiente
      description: Informe detalhes do ambiente onde o bug ocorreu.
      placeholder: "Ex.: Navegador, versão do sistema, SO, etc."
    validations:
      required: false
