name: Feature
description: Solicite uma nova funcionalidade ou melhoria
labels: ["enhancement"]
title: "[FEAT]: "
assignees: ["autor"]
body:
  - type: markdown
    attributes:
      value: |
        **Antes de criar a solicitação**, verifique se essa funcionalidade já não foi solicitada por outra pessoa.  
        Consulte as *issues* abertas/fechadas para evitar duplicidade.

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Faça uma breve descrição da funcionalidade ou melhoria que você gostaria de propor.
      placeholder: Explique resumidamente o que é e por que seria útil.
    validations:
      required: true

  - type: textarea
    id: informacoes-adicionais
    attributes:
      label: Informações Adicionais
      description: Inclua informações extras como soluções propostas, links, prints de tela, etc.
      placeholder: Adicione detalhes relevantes.
    validations:
      required: false

- type: markdown
    attributes:
      value: |
        ### 📋 Regras / Requisitos

        | Regra  | Descrição |
        |--------|-----------|
        | RN001  | Descreva a primeira regra ou requisito aqui. |
        | RN002  | Descreva a segunda regra ou requisito aqui. |
